### ISSUE TITLE
NPM or Yarn.

### ISSUE THREAD

**Issue by michaeldera** [michaeldera/edliz#34]
Using both Yarn and npm on the same project introduces a some redudancy into the project and we are better off discussing which of the two we would like to use and settle to. 

So for example, right now, if you run a push command in an IDE which is using npm as a default package management tool you run into errors because scripts in package.json will attempt to run 
`"pre-push": "yarn run lint"`. 

So I figure we should just go with one and discard the other.

**Comment by michaeldera** [comment]
@Noeza

**Comment by Noeza** [comment]
Hey, i would suggest we go with yarn i have a number of reasons why i would opt for it. Whats your take? We can go with what you comfortable with.

**Comment by Noeza** [comment]
NPM has significantly improved over the last few years as it had a major issues related to security and speed. But the most pressing one which even though they have addressed the issue its still not working as expected is the: npm.lock /yarn.lock. The function of the lock file is to ensure that the package manager respects the rules you have set for the packages you are installing. You dont want to run into a situation where, when you specify a version for your project, since npm does not respect those rules it tends to install the latest version which can break your code unexpectedly if it's not compatible with the latest versions of certain dependencies. 

NPM 6 has solved most of the problems but Yarn still outperforms it speed wise and is better at producing deterministic dependency trees, and to have better caching.

There is not need for us though to moved to yarn if the project was already built using npm.

**Comment by michaeldera** [comment]
Do not mind switching but wanted to understand. How much work do we need to do to switch, if it is worth it we can?

**Comment by Noeza** [comment]
Not much work needed actually.

**Comment by michaeldera** [comment]
Okay, let's do it then.
