### ISSUE TITLE
Application State Management.

### ISSUE THREAD

**Issue by Noeza** [michaeldera/edliz#5]
We need to add redux to the project so as to manage the state in store.

**Comment by michaeldera** [comment]
Did we eventually say we are using Redux here or MobX... I have not used both extensible but am quite open to either option.

**Comment by mcheartno** [comment]
After much research and thought, i have decided to use Mobx. The reasoning and motivation was due to the size and complexity of what we are building. Mobx fit better with what we are developing, and most importantly to note that it is an intuitive application, easy to learn and implement and also gives good performance. 
In as much as Redux has a large following and support, its a very opinionated library, which we us writing a  lot of boilerplate code. 
Please share your thoughts.

**Comment by michaeldera** [comment]
Have no problems with us going for Mobx. Having looked at it I share your sentiments so by all means, let us use Mobx. It does not have to much overhead when it comes to learning it so anyone who wants to contribute would be able to learn it.

**Comment by michaeldera** [comment]
@Noeza have you already started working on this?

**Comment by mcheartno** [comment]
yes, whats up?

**Comment by michaeldera** [comment]
@Noeza There are a couple of issues with the PR #11 . Check the errors on the console of the [dev version](https://edliz-dev.azurewebsites.net)

**Comment by michaeldera** [comment]
> 
> 
> @Noeza There are a couple of issues with the PR #11 . Check the errors on the console of the [dev version](https://edliz-dev.azurewebsites.net)

@Noeza let me know if you need me to put them up as bugs but the console will give you the issues.

**Comment by michaeldera** [comment]
@Noeza we can go over the app and see if there are any unintended side effects.. The only thing I noticed that was off was the preference panel had reverted to a version before the #11 which I have since fixed. Other than that I am happy. If you are too... as far as adding MobX is concerned, we can close this issue.

**Comment by Noeza** [comment]
@michaeldera Sure thing. I will go over it and check.

**Comment by Noeza** [comment]
What would you like us to focus on now?

**Comment by michaeldera** [comment]
> What would you like us to focus on now?

I will mention you on some issues
